# Generated by Django 3.2.7 on 2021-09-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_lecture_dep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='Department',
        ),
        migrations.AddField(
            model_name='lecture',
            name='Department',
            field=models.ManyToManyField(to='app.Department'),
        ),
    ]
