# Generated by Django 3.2.7 on 2021-09-11 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210911_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.department'),
        ),
    ]
